version: "3"
services:
  xmlcollect-receiver:
    container_name: ffp-xmlcollect-receiver
    build:
      context: .
      dockerfile: xmlcollect-receiver.Dockerfile
    restart: unless-stopped
    mem_limit: "2g"
    volumes:
      - ./tmpstor/:/tmpstor/
    env_file:
      - ./db.env
      - ./common.env
    environment:
      - TMPSTOR=/tmpstor/
      - PORT=17485
      - RECVTHREADS=128
    networks:
      ffp:
        ipv6_address: 2a03:4000:67:1:ff::444d
      dbs:

  cherry-status:
    container_name: ffp-status-cherry
    build:
      context: .
      dockerfile: cherry-status.Dockerfile
    restart: unless-stopped
    mem_limit: "1g"
    env_file:
      - ./db.env
      - ./common.env
    networks:
      - "www"
      - "dbs"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/cherry-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 4 -t 60 -b '[::]:8000' app

  messagesender:
    container_name: ffp-messagesender
    build:
      context: .
      dockerfile: messagesender.Dockerfile
    restart: unless-stopped
    mem_limit: "1g"
    env_file:
      - ./db.env
      - ./msgcfg.env
      - ./common.env
    networks:
      - "dbs"
      - "ffp"

  grafana:
    container_name: ffp-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    mem_limit: "512m"
    volumes:
      - ./grafana:/var/lib/grafana
    env_file:
      - ./grafana.env
    user: "1000"
    networks:
      - "www"
      - "dbs"
      - "ffp"


networks:
  ffp:
    name: ffp
    external: true
  dbs:
    name: dbs
    external: true
  www:
    name: www
    external: true
